enum PAGES {
  DASHBOARD = 'DASHBOARD',
  SECURITY_EVENT = 'SECURITY_EVENT',
  ANALYSIS = 'ANALYSIS',
  VULNERABILITY = 'VULNERABILITY',
  MITRE = 'MITRE',
  INTEGRITY_MONITORING = 'INTEGRITY_MONITORING',
  AGENT = 'AGENT',
}

export default PAGES;
