const VULNERABILITY_MOST_AFFECTED_AGENTS = 'Most Affected Agents';
const VULNERABILITY_MOST_COMMON_CVE = 'Most Common CVE';
const VULNERABILITY_PACKAGES_BY_CVE = 'Packages by CVE';
const VULNERABILITY_VULNERABILITY_BY_CRITICALITY =
  'Vulnerability by Criticality';
const MITRE_ATTACKS_BY_TECHNIQUE = 'Attacks by Technique';
const MITRE_TECHNIQUES_BY_AGENT = 'Techniques by Agent';

export const WidgetsNameList = [
  VULNERABILITY_MOST_AFFECTED_AGENTS,
  VULNERABILITY_MOST_COMMON_CVE,
  VULNERABILITY_PACKAGES_BY_CVE,
  VULNERABILITY_VULNERABILITY_BY_CRITICALITY,
  MITRE_ATTACKS_BY_TECHNIQUE,
  MITRE_TECHNIQUES_BY_AGENT,
];
